### ISSUE TITLE
Support KDBX 4 format / Argon2 key derivation function

### ISSUE THREAD

**Issue by sts10** [sseemayer/keepass-rs#11]
Just noticed that I get an `Encountered an invalid compression suite` error when I try to unlock a KeePass database that uses the "Argon2" key derivation function or the "AES-KDF (KDBX 4)" key derivation function. As of [version 2.3.0](https://keepassxc.org/blog/2018-02-28-2.3-released/), KeePassXC defaults to KDBX 4.0 and uses the Argon2 KDF.

I'm not sure if this issue with this crate is that it can't open KDBX 4 files or whether it can't do the Argon2 or AES KDF for KDBX 4.0 databases.

It'd be super cool if this crate could handle all these cases!

**Comment by sseemayer** [comment]
Yes, Argon2 is not currently supported and yes, it sounds like a good addition to this library. PRs are welcome, if you would like to contribute one. 

I will be travelling for the next three weeks but can try to drop in here every now and then if you have questions.

**Comment by sts10** [comment]
Gotcha. I'm a bit daunted by trying to make the change myself, but I can try!

I'm guessing that the error I'm seeing is from [this LOC](https://github.com/sseemayer/keepass-rs/blob/master/src/db_parse.rs#L182), so it's not really an "invalid compression suite" but rather an unsupported cipher. Maybe making this error message more descriptive would be a baby-step PR for me.

I'm also guessing that [`outer_cipher`](https://github.com/sseemayer/keepass-rs/blob/master/src/db_parse.rs#L139) is the KDF, as opposed `inner_ciper`?

Upon some digging, it looks like for KDBX 4, "key derivation function parameters are stored in the header field with ID 11 (KdfParameters)" ([source](https://keepass.info/help/kb/kdbx_4.html#extkdf)). So might need to write new parsing function(s) for KDBX 4?

**Comment by sseemayer** [comment]
Correcting the error message sounds like a good first step.

No, the KDF is not the `outer_cipher`. Let me walk you through how the KeePass crypto works, hopefully that will clear things out.

In a nutshell, the KeePass crypto has several stages (see also this gist for some details https://gist.github.com/msmuenchen/9318327):

1. [Derive a `composite_key` by concatenating password, keyfile, etc](https://github.com/sseemayer/keepass-rs/blob/cfac2523aadca9ac4583354e13c13d54bb907435/src/crypt.rs#L89-L101). 

2. [Transform that `composite_key` into a `transformed_key` by repeatedly doing an AES/ECB encryption of the key](https://github.com/sseemayer/keepass-rs/blob/cfac2523aadca9ac4583354e13c13d54bb907435/src/crypt.rs#L103-L131) in order to generate a high computational cost and protect against brute-forcing. Finally, hash the repeatedly encrypted key with SHA256 -- Probably, this is what you would have to replace with Argon2. 

3. [The `master_key` is a SHA256 hash of the concatenation of the `master_seed` and the `transformed_key`](https://github.com/sseemayer/keepass-rs/blob/cfac2523aadca9ac4583354e13c13d54bb907435/src/db_parse.rs#L65)

4. [The KeePass payload (several blocks of XML chunks) can now be decrypted using the `outer_cipher` - typically AES256 using CBC mode.](https://github.com/sseemayer/keepass-rs/blob/cfac2523aadca9ac4583354e13c13d54bb907435/src/db_parse.rs#L68-L69). Since the first few bytes of decrypted payload are stored in the KeePass database, you can [check here if everything went correctly until this step](https://github.com/sseemayer/keepass-rs/blob/cfac2523aadca9ac4583354e13c13d54bb907435/src/db_parse.rs#L71-L74).

5. [All blocks from the payload get assembled into an XML document representing the database](https://github.com/sseemayer/keepass-rs/blob/cfac2523aadca9ac4583354e13c13d54bb907435/src/db_parse.rs#L80-L129)

6. If a value in the XML (such as passwords) are marked as protected, the values can be decrypted using the `inner_cipher` (typically Salsa20), a `stream_key` and a fixed initialization vector.

**Comment by sseemayer** [comment]
Regarding what you will probably have to touch, the compression suite error comes from [this code checking for the `compression_flag` header value](https://github.com/sseemayer/keepass-rs/blob/cfac2523aadca9ac4583354e13c13d54bb907435/src/db_parse.rs#L40-L44). According to the KDBX 4 docs that you linked, it looks like the header format changed slightly here.

The KDBX 4 docs say:

> As of KDBX 4, key derivation function parameters are stored in the header field with ID 11 (KdfParameters).

I didn't check this but here is the [header parsing code that matches over the header field IDs](https://github.com/sseemayer/keepass-rs/blob/cfac2523aadca9ac4583354e13c13d54bb907435/src/db_parse.rs#L169-L217). I am slightly confused why this code won't encounter an ID of 11 as the docs specify, though.

**Comment by sseemayer** [comment]
Hmm, looking at the KDBX 4 docs, there might be a few more changes necessary. I unfortunately have to go right now but I hope that the notes that I left are still useful!

**Comment by sseemayer** [comment]
Just as a small update, I have started looking into KDBX4 and written a bunch of not-yet-functional code on the [dev-kdbx4 branch](https://github.com/sseemayer/keepass-rs/tree/dev-kdbx4). I still have to update the block decryption code, which is why there are Crypto errors.

**Comment by sseemayer** [comment]
Small update: I verified by patching some debug prints into the source code of KeepassXC that the keys seem to get transformed correctly also using the Argon2 KDF. Next up is verification of headers using Sha256/HMAC and the implementation of the [HmacBlockStream](https://github.com/keepassxreboot/keepassxc/blob/63aab99b9c03aa28194f432830a68d961c84e618/src/streams/HmacBlockStream.cpp) now used for the encrypted data.

**Comment by sseemayer** [comment]
I now managed to open a KDBX4 file and parse it, you can find the code in the [dev-kdbx4 branch](https://github.com/sseemayer/keepass-rs/tree/dev-kdbx4) until I did some more cleanups. If you get a chance, please let me know if this is working for you!

**Comment by sseemayer** [comment]
I've now merged into master together with some refactoring of the error handling and published v0.4.0 of the crate.

**Comment by sts10** [comment]
Sorry for my delayed response here -- I was traveling. 

This works great for [Medic](https://github.com/sts10/medic). Version 0.2.5 can successfully open a keepass 4.0 database! I added [a test](https://github.com/sts10/medic/blob/master/tests/integration-tests.rs#L86) to make sure.

Thanks for your hard work!
