### ISSUE TITLE
Opening of XML key file fails with Cryptography error

### ISSUE THREAD

**Issue by Narigo** [sseemayer/keepass-rs#12]
I've created a keyfile with my KeePassX 2.0.3 client. You can find them [as `*_file.kdbx` and `keyfile.key` here](https://github.com/Narigo/keepass-diff/tree/282470ad2d53b9db80044e3427a2a323f8d300ac/test).

Using my combination with the library only yields `Cryptography error` and will not open the file.

The main difference I can see is this: [Your `key` file](https://raw.githubusercontent.com/sseemayer/keepass-rs/0b84bc904491d02311a1c04581309edbc8c88f1e/tests/resources/test_key.key) is in binary format, showing binary data, while the one created by my Keypass client is [an XML file containing seemingly random data](https://raw.githubusercontent.com/Narigo/keepass-diff/282470ad2d53b9db80044e3427a2a323f8d300ac/test/keyfile.key).

As we talked about this in a [pull request in the keepass-diff repository](https://github.com/Narigo/keepass-diff/pull/7#issuecomment-495727013), I hope you can have a look into this.

You can use the example files from my repository if you like to create a test case around them.

**Comment by sts10** [comment]
Just realizing that I think I have the same issue with my KeePass-database-reading CLI, [Medic](https://github.com/sts10/medic). Did a quick test, which I describe below, but I can maybe dive deeper this weekend. 

## What I found in my hasty test

With a test database that uses the AES-KDF for KDBX 3.1 and a _binary_ key file, Medic was successful in opening the database. This wasn't surprising, as [the key file I used in the tests for Medic is a binary key file](https://github.com/sts10/medic/blob/master/tests/test-files/test_key_file).

However, when I changed the key file to an XML file, it failed with `Cryptography error`, as described above. 

Since this failure happened on with a database that uses KDBX 3.1, I don't think it's related to #11. Further evidence: keepass-rs (v0.3.3) gives a different error message when it attempts to open a 4.0 database: `Encountered an invalid compression suite`. But I could be wrong. 

## Possible explanations 

It's possible that _both_ keepass-diff and Medic implement the key file–reading functionality of keepass-rs incorrectly. But it also could be that keepass-rs isn't parsing XML key files correctly.

## Is XML a "legacy" format for key files? 

Separately, I will note that KeePassXC (I'm running v 2.3.4) displays a warning when you use an XML key file, about it being a "legacy" format: 
 
![Screen Shot 2019-05-30 at 4 20 59 PM](https://user-images.githubusercontent.com/4871664/58663543-c4668a00-82fa-11e9-951c-cb7929e57ce9.png)

So I'm guessing that the XML format will not be supported by KeePassXC in the future? (As you might guess, when you generate a key file with KeePassXC (above v 2.3.X), it generates a binary file, not XML.)

 That said, I still think it'd be good if keepass-rs could support as many types of key files as possible.

**Comment by sseemayer** [comment]
+1 on the reasoning and explanation. The [current keyfile parsing mechanism](https://github.com/sseemayer/keepass-rs/blob/cfac2523aadca9ac4583354e13c13d54bb907435/src/keyfile.rs#L46-L49) simply tries to parse the XML keyfile and takes the whole keyfile as the key should anything go wrong during parsing. 

I guess it would be a good idea to add some more debugging output to this mechanism to understand what is going wrong.

**Comment by sseemayer** [comment]
I managed to pin down what is different about your example database, but I don't know yet why that is / how to fix it.

Normally, a composite key is calculated as `composite_key = SHA256( key_elements.map(SHA256))` where `key_elements` is an array of all defined key elements such as passwords, key file content, etc. 

For all of the key files in my test set, the correct thing is to do a `composite_key = SHA256(SHA256(password))` or alternatively `composite_key = SHA256(SHA256(keyfile_content))`, but for the databases that you have created, the correct thing to do is `composite_key = SHA256(keyfile_content)` (one SHA256 operation fewer).

**Comment by sseemayer** [comment]
Apparently the one-fewer SHA256 operations is associated with legacy XML keyfiles: https://github.com/keepassxreboot/keepassxc/blob/2ee97ed1912fd068cd3484c439f2582a5d829ef4/src/keys/FileKey.cpp#L53-L56

**Comment by sseemayer** [comment]
a7a823e04318d2eea8ba10ab0afe7ef864e18c49 should fix things. I've also published v0.4.1 containing the fix.

**Comment by sts10** [comment]
Just tested this with my updated version of Medic (which [uses keepass-rs 0.4.1](https://github.com/sts10/medic/blob/master/Cargo.toml#L10)). Medic successfully opened an old KeePass database (created in 2017) that uses an XML file as a keyfile (note: it has a `.key` file extension). 👍
