### ISSUE TITLE
Group or entry with same title does not get into iterable

### ISSUE THREAD

**Issue by Narigo** [sseemayer/keepass-rs#24]
When having the same title twice in a group, only one will show up in the groups `iter()`. The other group or entry won't show up at all. It does not seem to be accessible through other means as well. Is there something I'm missing?

**Additional context**
I was trying to create a reproducible test for #16 - looks like I can't create an empty title (only `Some("")`). Anyways, trying to come up with such a test unearthed this issue.

**Comment by OliverEvans96** [comment]
I suspect it's because `Group` stores its entries in a `HashMap<String, Entry>` with titles as keys, and the first entry is overwritten when the second one is read.

https://github.com/sseemayer/keepass-rs/blob/32dd3c8b44b47b5fc19d614bbbb17ba6592e348e/src/db.rs#L274-L284

A few options that come to mind:
1. `entries: HashMap<String, Vector<Entry>>`
2. `entries: HashMap<String, Entry>`, but with a unique key (I'm not familiar with the keepass format - is there a unique key id?)
3. `entries: Vector<Entry>` instead of a `HashMap<String, Entry>`, and do lookups by looping over the whole entry. Seems similar to 2., but less efficient.

Anyone else have thoughs on this?
Oliver

**Comment by OliverEvans96** [comment]
Actually, the best of both worlds might be to store the values in `entries: Vec<Entry>`, but also have `title_map: HashMap<String, Vec<usize>>` that stores the indices of the elements of `entries` by title. We could have efficient iteration _and_ lookup.  Since `title_map` can be created during parsing at the same time that `entries` is being filled, it shouldn't introduce much execution time overhead, and the memory usage should also be quite small. 

I put together a little simplified demo:

```rust
use std::collections::HashMap;

struct XMLNode(String, String);

#[derive(Debug)]
struct Entry {
    title: String,
    password: String,
}

impl From<XMLNode> for Entry {
    fn from(n: XMLNode) -> Self {
        Entry {
            title: n.0,
            password: n.1,
        }
    }
}

#[derive(Debug)]
struct Group {
    entries: Vec<Entry>,
    title_map: HashMap<String, Vec<usize>>,
}

impl Group {
    pub fn new() -> Self {
        Self {
            entries: Vec::new(),
            title_map: HashMap::new(),
        }
    }

    pub fn get<'a>(&'a self, key: &str) -> Option<Vec<&'a Entry>> {
        match self.title_map.get(key) {
            Some(inds) => Some(inds.iter().map(|&i| &self.entries[i]).collect()),
            None => None,
        }
    }
}

impl IntoIterator for Group {
    type Item = Entry;
    type IntoIter = std::vec::IntoIter<Self::Item>;

    fn into_iter(self) -> Self::IntoIter {
        self.entries.into_iter()
    }
}

fn create_fake_xml() -> Vec<XMLNode> {
    [
        ("Gmail", "em4il"),
        ("GitHub", "cOdEz"),
        ("Coinbase", "btc4Lyfe"),
    ]
    .iter()
    .map(|(t, p)| XMLNode(t.to_string(), p.to_string()))
    .collect()
}

fn parse(xml: Vec<XMLNode>) -> Group {
    // Pretend this is XML to be parsed
    let mut group = Group::new();
    for n in xml.into_iter() {
        let entry: Entry = n.into();
        let index = group.entries.len() + 1;
        match group.title_map.get_mut(&entry.title) {
            Some(v) => {
                v.push(index);
            }
            None => {
                group.title_map.insert(entry.title.clone(), vec![index]);
            }
        }
        group.entries.push(entry);
    }

    group
}

fn main() {
    let xml = create_fake_xml();
    let group = parse(xml);
    println!("Parsed: {:#?}\n", group);
    println!("Lookup: {:#?}\n", group.get("Gmail"));
    println!("Iter: {:#?}\n", group.into_iter().collect::<Vec<_>>());
}
```

The biggest change this introduces, of course, it changing the return type of `get` from `Entry` to `Vec<Entry>` since title may not be unique within a group. It seems that there may also be multiple sibling groups with the same title, which would require reconsidering the current multi-level `.get(&["a","b","c"])` syntax. My above demo only implements single-level lookup.

Not sure why I decided to work on this today, but I learned quite a bit, and hopefully it generates some good discussion.

Cheers,
Oliver

**Comment by sseemayer** [comment]
Progress on this has been made with dda10ec6a11ba751b22aa9d65af4204c69968e51 since we are now storing a `Vec<Node>` instead of an `IndexMap<String, Entry>`. The `get` method for lookups will currently only return the first element meeting the criteria. 

To play devil's advocate, how crucial is having O(1) lookups in the entries for any reasonable database size, at the price of additional memory usage? I would argue that iterating over all elements in a group should be sufficient for any use cases that I can think of.
