### ISSUE TITLE
Always panics: Incorrect Key on x86_64

### ISSUE THREAD

**Issue by ShashaankHari** [sseemayer/keepass-rs#59]
This crate is used in [keepass-diff ](https://github.com/Narigo/keepass-diff/), I'm trying to check diffs with my two out of sync  .kdbx(kdbx4) its about 9-11Mb , but it always shows incorrect key specified. Built from aur https://aur.archlinux.org/packages/keepass-diff 

This is the full backtrace.
```
thread 'main' panicked at 'Error opening database A: IncorrectKey', src/main.rs:117:18
stack backtrace:
0:     0x55b96a052cbd - <unknown>
1:     0x55b96a07013c - <unknown>
2:     0x55b96a050931 - <unknown>
3:     0x55b96a0544b5 - <unknown>
4:     0x55b96a0541d1 - <unknown>
5:     0x55b96a054a46 - <unknown>
6:     0x55b96a054937 - <unknown>
7:     0x55b96a0531b4 - <unknown>
8:     0x55b96a054669 - <unknown>
9:     0x55b969f7fd73 - <unknown>
10:     0x55b969f7fe03 - <unknown>
11:     0x55b969f926d0 - <unknown>
12:     0x55b969f87976 - <unknown>
13:     0x55b969f87f95 - <unknown>
14:     0x55b96a04be6e - <unknown>
15:     0x55b969f96082 - <unknown>
16:     0x7fda3e5e9290 - <unknown>
17:     0x7fda3e5e934a - __libc_start_main
18:     0x55b969f7ffb5 - <unknown>
19:                0x0 - <unknown>
```

**Comment by sseemayer** [comment]
IncorrectKey would be thrown if the database was opened with an incorrect key (either wrong password, wrong keyfile, or both). 

I will close for now since there is not enough information to help debug this further. If you can provide a minimal example to reproduce (e.g. a testing database and a password), I am happy to re-open the issue :)

**Comment by ShashaankHari** [comment]
> IncorrectKey would be thrown if the database was opened with an incorrect key (either wrong password, wrong keyfile, or both).
I provided the proper password and keyfile, yet i get this error, the db opens on keepassxc, other android clients, but just not with keepass-diff

**Comment by sseemayer** [comment]
Could you please create a reproducible example, e.g. 

1. Make a copy of your database
2. Remove all entries and clear recycle bin
3. Change the password and keyfile
4. Check if the problem is still reproducible with the changed database
5. Share that database, password and keyfile, together with steps to reproduce
